displayErrorDetails: true
addContentLengthHeader: false
database:
  driver: mysql
  host: localhost
  database: i-content
  username: root
  password: 12345678
  collation: utf8_general_ci
logger:
  name: cms-i-app