displayErrorDetails: true
addContentLengthHeader: false
database:
  driver: mysql
  host: mysql
  database: i-content
  username: root
  password: 123456
  collation: utf8_general_ci
logger:
  name: cms-i-app